### ISSUE TITLE
Need descriptions for extra ophys metadata

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/leifer_lab_to_nwb#3]
### Volume scanning

In `zScan.json`...

```
        volume_scanning_column_descriptions = {
            "latency_shift_permutation": "",
            "etl_calibration_min_depth": "",
            "etl_calibration_max_depth": "",
            "piezo_etl_clock_lock", "",
            "etl_depth_per_micrometer": "",
            "etl_vmin": "",
            "etl_vmax": "",
            "waveform_type": "The generic shape of the waveform.",
            "waveform": "The full signature of the waveform", # TODO, what units?
        }
```

### Volume direction

In `other-volumeMetadataUtilities.txt`, what is the meaning of the `direction` column?

### 

In `other-frameSynchronous.txt`, what are...

- `Piezo position (V)`
- `Piezco direction`
- `Ludl X/Y`
- Is there special meaning to `Volume index` value of `-1`? (does not match IDs from the `other-volumeMetadataUtilities.txt` file)

**Comment by CodyCBakerPhD** [comment]
@emosb Do you have any advice on these fields? I'd like to map a text description onto each of these values in the respective JSON file contents

**Comment by emosb** [comment]
So direction indicates which way we are moving through the worm's head to take the current volume - we start outside the head and move until we are outside the head on the other side (a single volume), and then change the direction and come back until we are at the original z depth (the second volume). I believe this is what is meant by direction. 

To clarify this point, the voltage supplied to the electrically tunable lens will oscillate somewhere between 0 and 5 volts. When the voltage is decreasing, the "direction" is 1, and when the voltage is increasing, the "direction" is -1 (as seen in the other-frameSynchronous.txt file).

**Comment by emosb** [comment]
In other-frameSynchronous.txt, the Piezo (V) is referring to the voltage supplied to the instrument which is physically scanning over the z space. In our case I believe this historically used to be a Piezoelectric motor, but is now an electrically tunable lens (I will check on this), so the header may be inaccurate with regards to the instrument.

The piezo direction column stores +/- 1 depending on the direction with which we are moving through the worm's head (see above comment). 

I will ask about the Ludl X/Y columns. I think this may be a header carried over from another setup in the lab which has a motorized stage. The pump probe does not have a motorized stage and likely doesn't need these columns (which is why they are constant 0). I will confirm with Sophie that these columns are not necessary for this project.

The initial VolumeIndex of -1 is likely becuase the first volume starts midway through the worm's head (due to the stochasticity of when we hit record) so this partial volumn is given the index -1 so it is excluded from the data.

**Comment by CodyCBakerPhD** [comment]
Great, thank you!

So if I just record the depth at each frame, the direction (aside from the first) could be derivable based on the sign of the difference for each frame? I might not include it in that case

Any ideas for descriptions on the following fields from the `zScan.json` ? And confirmations that my guess for descriptions on the waveform ones are accurate?


```
        volume_scanning_column_descriptions = {
            "latency_shift_permutation": "",
            "etl_calibration_min_depth": "",
            "etl_calibration_max_depth": "",
            "piezo_etl_clock_lock", "",
            "etl_depth_per_micrometer": "",
            "etl_vmin": "",
            "etl_vmax": "",
            "waveform_type": "The generic shape of the waveform.",
            "waveform": "The full signature of the waveform", # TODO, what units?
        }
```

**Comment by CodyCBakerPhD** [comment]
@emosb Pinging again on these descriptions

**Comment by CodyCBakerPhD** [comment]
Not including these any more
